"""atualizando modelos user com dados faltantes 17/11/2025

Revision ID: 28b4ac754281
Revises: b631295e91bd
Create Date: 2025-11-17 01:30:56.908048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28b4ac754281'
down_revision: Union[str, Sequence[str], None] = 'b631295e91bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('surname', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'surname')
    # ### end Alembic commands ###
