"""adicionando campo update_at 20_11_2025

Revision ID: 6cdec46cb17c
Revises: 28b4ac754281
Create Date: 2025-11-20 18:22:40.462843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cdec46cb17c'
down_revision: Union[str, Sequence[str], None] = '28b4ac754281'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_sessions', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_sessions', 'updated_at')
    # ### end Alembic commands ###
