"""atualizando models

Revision ID: b631295e91bd
Revises: 80914a1f3d43
Create Date: 2025-11-16 00:17:30.193413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b631295e91bd'
down_revision: Union[str, Sequence[str], None] = '80914a1f3d43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=200), nullable=False))
    op.add_column('users', sa.Column('date_of_birth', sa.DATE(), nullable=False))
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_column('users', 'date_of_birth')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
