"""01.09.2026_atualizando a tabela de outbox para novo status e duas novas colunas

Revision ID: ca9163c93ce6
Revises: 631fd4384bca
Create Date: 2026-01-09 22:14:35.231858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca9163c93ce6'
down_revision: Union[str, Sequence[str], None] = '631fd4384bca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE outbox_status_enum ADD VALUE IF NOT EXISTS 'PROCESSING'")
    op.add_column('outbox', sa.Column('failed_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('outbox', sa.Column('next_attempt_at', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outbox', 'next_attempt_at')
    op.drop_column('outbox', 'failed_at')
    # ### end Alembic commands ###
