"""criando a tabela de verificacao de email para sign e possiveis logins futuros

Revision ID: e47036eb8441
Revises: c271a8881d7c
Create Date: 2025-11-24 16:48:32.698745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e47036eb8441'
down_revision: Union[str, Sequence[str], None] = 'c271a8881d7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_email_verifications',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('user_id', sa.String(length=26), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_user_email_verifications_user_id'), 'user_email_verifications', ['user_id'], unique=False)
    op.create_index('uq_user_email_verifications_active_per_user', 'user_email_verifications', ['user_id'], unique=True, postgresql_where=sa.text('verified_at IS NULL AND revoked_at IS NULL'))
    op.add_column('users', sa.Column('is_email_verified', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('email_verified_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=True)
    op.drop_column('users', 'email_verified_at')
    op.drop_column('users', 'is_email_verified')
    op.drop_index('uq_user_email_verifications_active_per_user', table_name='user_email_verifications', postgresql_where=sa.text('verified_at IS NULL AND revoked_at IS NULL'))
    op.drop_index(op.f('ix_user_email_verifications_user_id'), table_name='user_email_verifications')
    op.drop_table('user_email_verifications')
    # ### end Alembic commands ###
